const wordList = [
    "Seau",
    "Toit",
    "Nez",
    "Mât",
    "Roue",
    "Lit",
    "Chat",
    "Gant",
    "Feu",
    "Boue",
    "Tasse",
    "Tête",
    "Tonneau",
    ["Dame", "Timmy"],
    "Terre",
    "Télé",
    "Toge",
    ["Toque","Dague"],
    "Teuf",
    "Dobby",
    "Nazi",
    "Natte",
    "Nonne",
    "Nem",
    "Nord",
    "Nylon",
    "Niche",
    "Nougat",
    "Navet",
    ["Nappe", "Nabot"],
    "Maison",
    // "Mite",
    // "Mine (crayon, tête, arme",
    // "Momie",
    // "Mare",
    // "Mûle",
    // "Magie",
    // "muguet",
    // "Mafieux",
    // "Moby",
];

const highestWord = wordList.length - 1;